### ISSUE TITLE
Speed up xgb gpu even more

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/h2o4gpu#213]
See also TODO or OPTMARK in updater_gpu_hist.cu:

* For good-sized data sets, overall, 60% of time spent in UpdatePositionSparse due to bad memory access patterns.  The waiting is about 70%, so if improved could speed things up by 2X overall.

* BuildHist is slower than could be due to 50% waiting due to memory contention in atomics.  Liked we talked about long ago, should try caching and push cached in atomics.

* Lots of D2D copies of pretty big chunks of data.  Unsure what it's doing, but seems unnecessary or some out-of-place operation could be made in-place.

* Since currently not memory bandwidth limited (just contention/waiting limited), can try reducing occupancy for kernels and overload the GPU with multiple tasks.  E.g., 3 embarrassingly parallel jobs on same GPU if reduce occupancy to 33% instead of 100%.

**Comment by RAMitchell** [comment]
The new version I'm working on should be able to replace the gpu_hist version when complete. 

I've used a binary search instead for updatepositionsparse so that might improve performance. 

Each kernel now processes one node at a time giving us the ability to do some more optimizations on the histogram builder. E.g. shared memory

D2d copies will be in updatepositionsparse I think. Binary search approach no longer requires this.

Occupancy idea is interesting. 

I will get a usable version of the new algo on within in the next week or two then book a trip to mountain view and we can look at it then if that suits.

**Comment by pseudotensor** [comment]
Thanks, good to know.  I won't try to improve the existing algo.  It'll be interesting how things work out as far as latency issues go (biggest issue with current algo).

**Comment by pseudotensor** [comment]
Also, old algo had very little use of registers or shared memory.

**Comment by pseudotensor** [comment]
And actually, nvvp shows very low memory bandwidth usage across all types of memory.

**Comment by pseudotensor** [comment]
New xgb algo.
