### ISSUE TITLE
k-means performance on P100

### ISSUE THREAD

**Issue by PlayMen** [h2oai/h2o4gpu#289]
Hi, 
according to https://github.com/h2oai/h2o4gpu/blob/master/presentations/benchmarks.pdf
it is stated that H2O can fit k-means with 1000 iterations and 1000 clusters in 30.8 sec. I haven't found information what library version was used.

I cannot reproduce such a performance on my P100. I use code from https://github.com/h2oai/h2o4gpu/blob/master/examples/py/demos/H2O4GPU_KMeans_Homesite.ipynb

Also - I see that default number of iterations = 300, not 1000 iterations by default as stated there.
When I run it, it terminated by threshold, so I have ~1o seconds to converge. When I set tol=0.0, I need 48 seconds to do 1000 iterations, not 30 seconds. Why is there such a difference?

OS: Linux
Installed from https://s3.amazonaws.com/artifacts.h2o.ai/releases/bleeding-edge/ai/h2o/h2o4gpu/0.0.4/h2o4gpu-0.0.4-py36-none-any.whl
Python 3.6
CUDA 8
GPU: 1x Tesla P100
CPU: Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz
RAM: 125GB

**Comment by mdymczyk** [comment]
@PlayMen that benchmark was done around May/June so using quite an old version. The defaults at that time were `tol=1E-3` and `max_iter=1000`. Since that time we have fixed a lot of bugs (which also negatively impacted performance) and added some performance improvements - that's why you might be seeing a pretty big performance boost. 

We'll have to rerun this benchmark sometime next week when I fix a multi-gpu bug and an issue with memory consumption for the `k-means||` initialization.

**Comment by PlayMen** [comment]
Thanks for your reply!

Is it possible to find out the number of iteration that were performed by algorithm?

**Comment by mdymczyk** [comment]
You can run @PlayMen we don't return that value but you can set `verbose=1` (when creating KMeans object) and it will be printed in the logs.

**Comment by PlayMen** [comment]
Thanks, it helped! I also see in output Timetransfer: 1.86826 - is it overall device to host and host to device time?

**Comment by mdymczyk** [comment]
@PlayMen no that's only the initial host -> device transfer of data and initial centroids. This value also should be improved soonish (next week?).
