### ISSUE TITLE
Update family argument in ElasticNet solver

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#431]
* Update `family` argument in `ElasticNet` solver to something more obvious. For example "binomial" for logistic regression and "gaussian" for regression.

**Comment by ledell** [comment]
If we decide to split ElasticNet into separate regressor/classifier functions in Python/R, then maybe we could keep the family arg on the [backend](https://github.com/h2oai/h2o4gpu/blob/master/src/common/elastic_net_ptr.h) only (because it would be redundant since we only support one regression family and one classification family).
