### ISSUE TITLE
Consider splitting ElasticNet solver to ElasticNetRegressor/Classifier

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#432]
This is currently controlled through the family argument, but since we are separating regressor/classifier functions elsewhere, then maybe it makes sense to do it here as well (and hide the family arg).

**Comment by mdymczyk** [comment]
> but since we are separating regressor/classifier functions elsewhere

Are we? I must have missed that conversation, for which Python APIs are we doing this?

I still think for now we should stick to how Scikit is doing things and don't see any ElasticNetRegressor/Classifier there.

**Comment by navdeep-G** [comment]
@mdymczyk https://github.com/h2oai/h2o4gpu/blob/master/src/interface_py/h2o4gpu/solvers/xgboost.py

And I am not sure if thats the right solution. Right now the class is called `ElasticNetH2O`. We can leave it as is or we can make the regressor/classifier classes just like we did for xgboost (as shown above).

**Comment by mdymczyk** [comment]
@navdeep-G ah yes I know about those, but they are based on scikit http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

**Comment by navdeep-G** [comment]
@mdymczyk Yes, but it gets confusing when we have those split into two classes while others do not.

**Comment by navdeep-G** [comment]
We alreayd split ElasticNet into Lasso, Ridge, Linear, Logistic.

However, the `Logistic` class is limited to scikit params. I don't believe it has the full capability of what we offer in h2o4gpu.

**Comment by mdymczyk** [comment]
@navdeep-G let me put it this way: I'm ok with having more classes than Scikit has if we think they will benefit us but I also think we should have all the classes Scikit has (naming and params) for users to switch as easily as possible. Otherwise with our current baggage of rewriting scikit classes etc. it will get very messy.

**Comment by navdeep-G** [comment]
@mdymczyk Yes, thats fine. But I am not doing this for scikit mainly. I am considering the R api here.

**Comment by navdeep-G** [comment]
No one uses scikit in R. Its irrelevant in that regard.

**Comment by mdymczyk** [comment]
@navdeep-G yes that's why I think R API shouldn't influence the Python API. I mean how many people will use both? That would be one of the very few reasons I'd consider to make both as similar as possible. Lets strive Python API to be as close to Scikit and R as close to whatever is the most commonly used R library.

**Comment by navdeep-G** [comment]
@mdymczyk Not really influencing here. I am just trying to find some consistency in the R api that makes sense. So far I have not found it.

**Comment by mdymczyk** [comment]
Right, that sounds good. Do you have time or are you swamped with stuff? If you're up for it, could you draft a high level API (no impl, just method signatures etc.) how you'd think it would work best? Preferably both in Python and R, since you're most experienced with both. Then we can discuss.

**Comment by ledell** [comment]
@mdymczyk We can definitely do things differently in R vs Python, but since we are auto-generating the R wrappers from Python, I guess the thought is that adding class/regr classes would make this auto-generation easier.  However, we could also consider just doing the class/regr split on the R side.

**Comment by navdeep-G** [comment]
@ledell @mdymczyk Lets just do the split on the R side. Seems feasible.

**Comment by ledell** [comment]
We can close this now since we did this on the R side here: https://github.com/h2oai/h2o4gpu/pull/430
