### ISSUE TITLE
Add instructions for installing h2o4gpu on AWS

### ISSUE THREAD

**Issue by navdeep-G** [h2oai/h2o4gpu#464]

**Comment by ben-campbell** [comment]
I just documented this for sales engineering a couple days ago:

# H2O4GPU Installation

This describes how to install H2O4GPU on a fresh AWS Ubuntu 16.0.4 GPU instance (tested on g3.4x, which has one Tesla M60).

### NVIDIA CUDA:

Dependencies:

```
sudo apt-get update -y
sudo apt-get install -y gcc
sudo apt-get install -y make
```

NVIDIA CUDA 9.0 — check [here](https://developer.nvidia.com/cuda-downloads) for up-to-date links (note that, as of 03/01/18 H2O4GPU does not support CUDA 9.1).

```
wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
sudo sh cuda_9.0.176_384.81_linux-run
```
Agree to terms (press SPACE to page down) and install with all defaults.

Verify drivers installed:

```
nvidia-smi
```

Environment variables:

```
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_HOME/lib64/:$CUDA_HOME/lib/:$CUDA_HOME/extras/CUPTI/lib64
```

### Python

To install Python3.6 via apt-get on Ubuntu 16.0.4:

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update -y
sudo apt-get install -y python3.6
sudo rm /usr/bin/python3
sudo ln -s /usr/bin/python3.6 /usr/bin/python3
sudo apt-get install -y python3.6-dev
sudo apt-get install -y python3-pip
```
### H2O4GPU

Dependencies:

```
sudo apt-get install libopenblas-dev pbzip2
```

Get and install python package:

```
wget https://s3.amazonaws.com/h2o-release/h2o4gpu/releases/stable/ai/h2o/h2o4gpu/0.1-nccl-cuda9/h2o4gpu-0.1.0-py36-none-any.whl
pip3 install h2o4gpu-0.1.0-py36-none-any.whl
```

Try H2O4GPU:

```
python3
>>> import h2o4gpu
>>> import numpy as np
>>> X = np.array([[1.,1.], [1.,4.], [1.,0.]])
>>> model = h2o4gpu.KMeans(n_clusters=2,random_state=1234).fit(X)
>>> model.cluster_centers_
array([[1. , 0.5],
       [1. , 4. ]])
```

**Comment by navdeep-G** [comment]
@ben-campbell Yep, will add that in. Thx!

**Comment by mdymczyk** [comment]
@ben-campbell @navdeep-G do we really need to add this to the repo? The first and last paragraphs are pretty much repeating https://github.com/h2oai/h2o4gpu#requirements and https://github.com/h2oai/h2o4gpu#user-installation. If possible I'd like to keep OS specific instructions in this repo to the bare minimum (like `sudo apt-get install libopenblas-dev pbzip2`) as in the (hopefully) near future we want to make this package more generic (so it also works on Centos/RHEL and CPU only systems like macbooks) and we'd have to make such instructions all those setups. It's easier just to point to a packages website which details how to do it.

I'd prefer to have as few such tutorials as possible in the repo because from experience people don't really update them down the road. 

If we really need it we can put it on our wiki somewhere.

**Comment by navdeep-G** [comment]
@mdymczyk I feel it’s not a big deal to have in the repo. I already have it in a branch. I can maintain it if needed.

**Comment by navdeep-G** [comment]
Maybe the q is why @ben-campbell had to make the instructions. Are we missing something?

**Comment by ben-campbell** [comment]
i don't think it's necessary for the repo... It's kind of redundant, I agree.
