### ISSUE TITLE
CUDA 9.1 support

### ISSUE THREAD

**Issue by mdymczyk** [h2oai/h2o4gpu#468]
CUDA 9.1 is not backwards compatible with 9.0. Currently it is failing to build/run with several errors. Need to look into why exactly and how to fix them.

We also need to figure out if/how we want to support both 9.0 and 9.1 at the same time.

**Comment by brycelelbach** [comment]
Any update on this?

**Comment by brycelelbach** [comment]
The compilation failure is happening because Thrust switched to a new `reduce` implementation (based on CUB) in CUDA 9.1. Specifically, this `transform_reduce` call fails:

https://github.com/h2oai/h2o4gpu/blob/master/src/gpu/include/cml/cml_blas.cuh#L155

`cub::DeviceReduce` which uses `<<<,>>>` to launch kernels, even in the device side code (cnp). `<<<,>>>` in device side launch rejects kernels that accepts by value a type with non-default copy ctor.

**Comment by brycelelbach** [comment]
```
// Nrm2.
template <typename T>
struct Square : thrust::unary_function<T, T> {
  __device__ T operator()(const T &x) {
    return x * x;
  }
};

template <typename T>
T blas_nrm2(cublasHandle_t handle, const vector<T> *x) {
  strided_range<thrust::device_ptr<T> > strided_x(
      thrust::device_pointer_cast(x->data),
      thrust::device_pointer_cast(x->data + x->stride * x->size), x->stride);
  T nrm2 = sqrt(thrust::transform_reduce(strided_x.begin(), strided_x.end(),
      Square<T>(), static_cast<T>(0.0), thrust::plus<T>()));
  return nrm2;
}
```

I think `Square` is the issue because the iterator's data types are builtin types for the failure I see, although fancy iterators are used...

**Comment by mdymczyk** [comment]
@brycelelbach we decided to only support 8.x and 9.0 for this release (0.2.0 which is planned for 26.03). We'll look into supporting newer CUDA versions after GTC, sorry for the inconvenience.

**Comment by mdymczyk** [comment]
Sorry @brycelelbach forgot to update this issue, looks like CUDA 9.1 compilation has been working fine for a few weeks now after we redid our build process with CMake. We'll try to get our hands on CUDA 9.2 asap to see if that one will also work out of the box.
