### ISSUE TITLE
Host R package documentation

### ISSUE THREAD

**Issue by terrytangyuan** [h2oai/h2o4gpu#602]
We now have R package documentation here: https://github.com/h2oai/h2o4gpu/tree/master/src/interface_r/docs

@angela0xdata Could you help us host it in a similar way to what's done for h2o-3 R API docs? Or tag anyone who's able to help with this.

cc: @ledell @navdeep-G

**Comment by angela0xdata** [comment]
Everything looks good locally. I'll work with Anmol to get these docs included in the build.

**Comment by terrytangyuan** [comment]
Thanks!

**Comment by abal5** [comment]
I'll put this into a Jenkinsfile stage so we can get it building.

**Comment by terrytangyuan** [comment]
@abal5 Could you point me to the documentation page? Perhaps add the link to R package's README?

**Comment by angela0xdata** [comment]
@terrytangyuan  http://h2o-release.s3.amazonaws.com/h2o4gpu/nightly/h2o4gpu-Rdocs/7/interface_r/docs/index.html
(Note an issue still exists with the top heading... and we still have no idea why it's getting cut off.)

**Comment by terrytangyuan** [comment]
Does it happen locally when you open the html? Also probably try previous versions of pkgdown.

**Comment by angela0xdata** [comment]
@Erin, no Anmol has been working on getting h2o4gpu R docs into the build and then uploaded to S3. 

Here is the S3 link:
http://h2o-release.s3.amazonaws.com/h2o4gpu/nightly/h2o4gpu-Rdocs/7/interface_r/docs/index.html

Also attaching a zip of the files when built locally:
[docs.zip](https://github.com/h2oai/h2o4gpu/files/2206364/docs.zip)

Regarding latest stable vs nightly, I don't know of a latest stable yet. I don't believe there have been any H2O4GPU releases since this issue was closed. (But I could be wrong.)

The docs will reside in the H2O4GPU box on docs.h2o.ai, just like other products. Currently, that box only has links to the README, the Apache license, and a "download" link pointing to github. I can add it to the R box also.
